import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout/Layout";
import HomeLayout from "@/components/Layout/HomeLayout/HomeLayout";
import Service from "./Service";
import About from "./About";
import Footer from "./Footer";
import Contact from "./Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeLayout>
          <>
            <section
              className="w-full md:w-auto  bg-cover bg-no-repeat bg-center "
              style={{
                backgroundImage: `url("/images/hero.webp")`,
                height: "80vh",
              }}
            >
              <h1 className="text-6xl font-bold text-center pt-20 text-white animate-pulse ">
                Transportation At Its Finest
              </h1>
              <h2 className="text-3xl font-bold text-center text-white pt-6  ">
                Affordable luxury car service in Pakistan
              </h2>
              <div className="grid place-items-center">
                <button className="  rounded-full bg-orange-500 text-white hover:bg-pink-500 font-bold py-4 px-8 mt-5  items-center">
                  Call US Now
                </button>
              </div>
            </section>

            <Service />

            <section>
              <div
                className="w-full md:w-auto  bg-cover bg-no-repeat bg-center "
                style={{
                  backgroundImage: `url("/images/limo.webp")`,
                  height: "80vh",
                }}
              ></div>
              <h2 className="text-5xl font-bold text-center text-orange-500 pt-6 ">
                PROFESSIONAL TRANSPORTATION SERVICE TEAM
              </h2>
              <p className="px-40 py-6 text-lg">
                HMS limo service in pakistan With just one call, our support
                team will arrange all of your ground transportation and deliver
                consistent, professional chauffeured transportation services
                throughout Pakistan area. Our chauffeured services offer
                businesses and frequent travelers a true one source solution for
                all their private transportation needs. HMSLimousine provides
                quick and easy quotes for your travel needs.
              </p>
              <div className="grid place-items-center">
                <button className="  rounded-full bg-orange-500 text-white hover:bg-pink-500 font-bold py-4 px-8 mt-5  items-center">
                  Call US Now
                </button>
              </div>
            </section>

            <About />
            <Contact />
            <Footer />
          </>
        </HomeLayout>
      </Layout>
    </>
  );
}
