import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout/Layout";
import HomeLayout from "@/components/Layout/HomeLayout/HomeLayout";
import { HeroForm } from "@/components/Header/HeroForm";
import { Services } from "@/components/Home/Services";
import { About } from "@/components/Home/About";
import { Fleet } from "@/components/Home/Fleet";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeLayout>
          <>
            <HeroForm />
            <Services />
            <About />
            <Fleet />
            <Footer />
          </>
        </HomeLayout>
      </Layout>
    </>
  );
}
